# -*- coding: utf-8 -*-
"""18 march.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HW1fWceLqi-lklSPCc1MDlvfKrcTsldd
"""

import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

data = pd.read_csv('/content/pima-indians-diabetes.data.csv')

data

data.shape

X = data.iloc[:,:8]

y = data.iloc[:,8]

X

y

seed=7
test_size=0.30
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=test_size,random_state=seed)

model=XGBClassifier()
model.fit(X_train,y_train)

y_pred=model.predict(X_test)
predictions=[round(value) for value in y_pred]
print(predictions)

accuracy=accuracy_score(y_test,predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

data1=pd.read_csv('/content/Water_Potability_Data.csv')

data1

